/*
 * A279214 -- exact meet-in-the-middle evaluator.
 *
 * Count permutations sigma of {1,...,n} satisfying
 *
 *   |sigma(i+1)-sigma(i)| >= 3,  1 <= i <= n-1,
 *   |sigma(i+2)-sigma(i)| >= 3,  1 <= i <= n-2.
 *
 * This program differs from 279214_01.c at the whole-permutation level.
 * Program 01 propagates prefixes all the way to length n.  Program 02
 * stops at the middle and joins two independently counted half paths.
 * Both necessarily use the same width-two local fact: when a value is
 * appended, only the preceding two values create new constraints.
 *
 * Let P_k(S,a,b) be the number of valid orderings of the k-element set S
 * ending in a,b.  Put m=floor(n/2), r=n-m, and T=[n]\S.  Reversing a
 * valid right half shows that the number of right halves beginning c,d is
 * P_r(T,d,c).  Therefore
 *
 *   a(n) = sum_{|S|=m} sum_{a,b in S; c,d in T}
 *          P_m(S,a,b) P_r(T,d,c)
 *          [|a-c|>=3] [|b-c|>=3] [|b-d|>=3].
 *
 * Only the three displayed inequalities cross the split.  The apparent
 * four-endpoint join is reduced as follows.  For R(c,d)=P_r(T,d,c), set
 *
 *   q_b(c) = sum_{d in T, |d-b|>=3} R(c,d).
 *
 * Then a left state P_m(S,a,b) is multiplied by
 *
 *   sum_{c in T, |c-a|>=3, |c-b|>=3} q_b(c).
 *
 * Since a forbidden neighborhood contains at most five values, q_b(c)
 * and the final c sum are obtained by subtracting only local entries from
 * row totals.  This avoids an O(n^4) endpoint join for every split.
 * For even n, S and T give reversal-paired full permutations, so only
 * S<T is joined and the result is doubled.
 *
 * Half paths are generated by sparse subset DP, but only through length
 * ceil(n/2).  Two hash layers are used.  Before a growing layer is filled,
 * its obsolete buffer is released and a likely final capacity is reserved;
 * unlike incremental growth, this normally avoids holding old and new
 * large buffers simultaneously.  This is important near n=22 or n=23.
 *
 * Value complementation v -> n-1-v is also used.  A hash slot stores the
 * combined count of the two reflected states.  Every ordered-pair state
 * has orbit size two, so lookup divides the stored value by two to recover
 * P_k(S,a,b).  --no-symmetry disables this optimization; --check compares
 * the two versions on small n.
 *
 * Safety:
 *   - half-path counts and the final positive sum are bounded by n!;
 *   - 34! < 2^128, so unsigned 128-bit arithmetic is exact for n<=34;
 *   - additions, subtractions, products, key packing, table growth, and
 *     allocation sizes are checked anyway;
 *   - --memory-mib is a hard budget for all DP hash-table buffers;
 *   - a range run flushes b279214_02_part.txt after each completed term
 *     and renames it atomically to b279214_02.txt only after success.
 *
 * The integer type is safe through n=34, but the exponential half-state
 * table normally sets a much smaller practical limit.
 *
 * Build:
 *
 *   clang -O3 -std=c11 -Wall -Wextra -Wpedantic \
 *     279214_02.c -o 279214_02
 *
 * Usage:
 *
 *   ./279214_02
 *   ./279214_02 --term 22 --memory-mib 6144
 *   ./279214_02 --upto 22 --memory-mib 6144
 *   ./279214_02 --no-symmetry --term 12
 *   ./279214_02 --check
 *
 * Reference:
 *   https://oeis.org/A279214
 */

#define _POSIX_C_SOURCE 200809L

#include <errno.h>
#include <inttypes.h>
#include <limits.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>

#ifdef __APPLE__
#include <mach-o/dyld.h>
#endif

#if !defined(__SIZEOF_INT128__)
#error "279214_02 requires compiler support for unsigned __int128"
#endif

__extension__ typedef unsigned __int128 uint128_t;

#define SEQUENCE_OFFSET 0
#define DEFAULT_MAX_N 17
#define MAX_SUPPORTED_N 34
#define REFERENCE_MAX_N 22
#define OEIS_MAX_N 17
#define DEFAULT_CHECK_N 17
#define DIRECT_CHECK_MAX_N 10
#define SYMMETRY_CHECK_MAX_N 12
#define DEFAULT_MEMORY_MIB UINT64_C(1024)
#define MIN_MEMORY_MIB UINT64_C(16)
#define INITIAL_CAPACITY ((size_t)16)
#define LOAD_NUMERATOR ((size_t)7)
#define LOAD_DENOMINATOR ((size_t)10)
#define ENDPOINT_BITS 6U
#define ENDPOINT_MASK UINT64_C(63)
#define STATE_SHIFT (2U * ENDPOINT_BITS)

_Static_assert(MAX_SUPPORTED_N < 64,
               "the value-set mask must fit in uint64_t");
_Static_assert(MAX_SUPPORTED_N + STATE_SHIFT < 64,
               "the packed state key must fit in uint64_t");

/*
 * n=0..17 are from the OEIS b-file.  n=18..22 are independently produced
 * by 279214_01.c and are included as regression values for this different
 * meet-in-the-middle completion algorithm.
 */
static const char *const reference_terms[REFERENCE_MAX_N + 1] = {
    "1",
    "1",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "0",
    "2",
    "40",
    "792",
    "15374",
    "281434",
    "5089060",
    "93082532",
    "1743601076",
    "33694028152",
    "674469010966",
    "14015093037280",
    "302588959796950",
    "6789036995197166",
    "158247765964629918"
};

typedef struct {
    uint64_t low;
    uint64_t high;
} Count128;

typedef struct {
    uint64_t key_plus_one;
    Count128 count;
} StateSlot;

typedef struct {
    size_t limit;
    size_t in_use;
    size_t peak;
} MemoryBudget;

typedef struct {
    StateSlot *slots;
    size_t capacity;
    size_t size;
    MemoryBudget *budget;
} StateMap;

typedef struct {
    uint64_t prefix_transitions;
    uint64_t split_subsets;
    uint64_t joined_endpoint_pairs;
    size_t left_states;
    size_t right_states;
    size_t peak_bytes;
    double build_seconds;
    double join_seconds;
    double total_seconds;
} MitmStats;

typedef enum {
    RUN_UPTO,
    RUN_TERM,
    RUN_CHECK
} RunMode;

static void die(const char *message)
{
    fprintf(stderr, "error: %s\n", message);
    exit(EXIT_FAILURE);
}

static double monotonic_seconds(void)
{
    struct timespec now;
    if (clock_gettime(CLOCK_MONOTONIC, &now) != 0) {
        die("clock_gettime failed");
    }
    return (double)now.tv_sec + (double)now.tv_nsec / 1000000000.0;
}

static size_t checked_product_size(size_t left, size_t right)
{
    if (left != 0U && right > SIZE_MAX / left) {
        die("allocation size overflow");
    }
    return left * right;
}

static int parse_n(const char *text, const char *label)
{
    char *end = NULL;
    errno = 0;
    long value = strtol(text, &end, 10);
    if (errno != 0 || end == text || *end != '\0' ||
        value < SEQUENCE_OFFSET || value > MAX_SUPPORTED_N) {
        fprintf(stderr, "error: %s must be in %d..%d: %s\n",
                label, SEQUENCE_OFFSET, MAX_SUPPORTED_N, text);
        exit(EXIT_FAILURE);
    }
    return (int)value;
}

static uint64_t parse_memory_mib(const char *text)
{
    char *end = NULL;
    errno = 0;
    unsigned long long value = strtoull(text, &end, 10);
    uint64_t maximum = (uint64_t)(SIZE_MAX / (size_t)UINT64_C(1048576));
    if (errno != 0 || end == text || *end != '\0' ||
        value < MIN_MEMORY_MIB || value > maximum) {
        fprintf(stderr,
                "error: MEMORY_MIB must be in %" PRIu64 "..%" PRIu64
                ": %s\n",
                MIN_MEMORY_MIB, maximum, text);
        exit(EXIT_FAILURE);
    }
    return (uint64_t)value;
}

static Count128 count_zero(void)
{
    Count128 result = {0, 0};
    return result;
}

static Count128 count_from_u64(uint64_t value)
{
    Count128 result = {value, 0};
    return result;
}

static bool count_is_zero(Count128 value)
{
    return value.low == 0 && value.high == 0;
}

static bool count_equal(Count128 left, Count128 right)
{
    return left.low == right.low && left.high == right.high;
}

static int count_compare(Count128 left, Count128 right)
{
    if (left.high != right.high) {
        return left.high < right.high ? -1 : 1;
    }
    if (left.low != right.low) {
        return left.low < right.low ? -1 : 1;
    }
    return 0;
}

static void count_add_to(Count128 *destination, Count128 addend)
{
    uint64_t old_low = destination->low;
    uint64_t new_low = old_low + addend.low;
    uint64_t carry = new_low < old_low ? UINT64_C(1) : UINT64_C(0);

    uint64_t old_high = destination->high;
    uint64_t new_high = old_high + addend.high;
    if (new_high < old_high) {
        die("unsigned 128-bit addition overflow");
    }
    uint64_t final_high = new_high + carry;
    if (final_high < new_high) {
        die("unsigned 128-bit addition overflow");
    }
    destination->low = new_low;
    destination->high = final_high;
}

static Count128 count_subtract(Count128 minuend, Count128 subtrahend)
{
    if (count_compare(minuend, subtrahend) < 0) {
        die("internal negative count in meet-in-the-middle join");
    }
    Count128 result;
    result.low = minuend.low - subtrahend.low;
    uint64_t borrow = minuend.low < subtrahend.low
                          ? UINT64_C(1) : UINT64_C(0);
    result.high = minuend.high - subtrahend.high - borrow;
    return result;
}

static Count128 count_halve(Count128 value)
{
    if ((value.low & UINT64_C(1)) != 0) {
        die("internal odd reflected-orbit count");
    }
    Count128 result;
    result.low = (value.low >> 1U) | (value.high << 63U);
    result.high = value.high >> 1U;
    return result;
}

static uint128_t count_to_u128(Count128 value)
{
    return ((uint128_t)value.high << 64U) | (uint128_t)value.low;
}

static Count128 count_from_u128(uint128_t value)
{
    Count128 result = {(uint64_t)value, (uint64_t)(value >> 64U)};
    return result;
}

static Count128 count_multiply(Count128 left, Count128 right)
{
    uint128_t a = count_to_u128(left);
    uint128_t b = count_to_u128(right);
    uint128_t maximum = ~(uint128_t)0;
    if (a != 0 && b > maximum / a) {
        die("unsigned 128-bit multiplication overflow");
    }
    return count_from_u128(a * b);
}

static Count128 parse_count(const char *text)
{
    uint128_t value = 0;
    for (const unsigned char *p = (const unsigned char *)text;
         *p != '\0'; ++p) {
        if (*p < (unsigned char)'0' || *p > (unsigned char)'9') {
            die("invalid built-in decimal value");
        }
        unsigned digit = (unsigned)(*p - (unsigned char)'0');
        uint128_t maximum = ~(uint128_t)0;
        if (value > (maximum - (uint128_t)digit) / (uint128_t)10U) {
            die("built-in decimal value exceeds unsigned 128-bit range");
        }
        value = value * (uint128_t)10U + (uint128_t)digit;
    }
    return count_from_u128(value);
}

static int fprint_count(FILE *stream, Count128 count)
{
    char digits[40];
    size_t length = 0;
    uint128_t value = count_to_u128(count);
    do {
        digits[length++] = (char)('0' + (unsigned)(value % 10U));
        value /= 10U;
    } while (value != 0);
    while (length != 0U) {
        if (fputc((unsigned char)digits[--length], stream) == EOF) {
            return -1;
        }
    }
    return 0;
}

static void budget_reserve(MemoryBudget *budget, size_t bytes)
{
    if (bytes > budget->limit - budget->in_use) {
        fprintf(stderr,
                "error: DP memory budget exceeded: need another %.1f MiB "
                "with %.1f/%.1f MiB already in use; rerun with a larger "
                "--memory-mib value\n",
                (double)bytes / 1048576.0,
                (double)budget->in_use / 1048576.0,
                (double)budget->limit / 1048576.0);
        exit(EXIT_FAILURE);
    }
    budget->in_use += bytes;
    if (budget->peak < budget->in_use) {
        budget->peak = budget->in_use;
    }
}

static void budget_release(MemoryBudget *budget, size_t bytes)
{
    if (bytes > budget->in_use) {
        die("internal memory-budget underflow");
    }
    budget->in_use -= bytes;
}

static StateSlot *allocate_slots(MemoryBudget *budget, size_t capacity)
{
    size_t bytes = checked_product_size(capacity, sizeof(StateSlot));
    budget_reserve(budget, bytes);
    StateSlot *slots = calloc(capacity, sizeof(StateSlot));
    if (slots == NULL) {
        fprintf(stderr,
                "error: could not allocate %.1f MiB for a DP table\n",
                (double)bytes / 1048576.0);
        exit(EXIT_FAILURE);
    }
    return slots;
}

static void free_slots(MemoryBudget *budget, StateSlot *slots,
                       size_t capacity)
{
    size_t bytes = checked_product_size(capacity, sizeof(StateSlot));
    free(slots);
    budget_release(budget, bytes);
}

static uint64_t mix_key(uint64_t value)
{
    value ^= value >> 30U;
    value *= UINT64_C(0xbf58476d1ce4e5b9);
    value ^= value >> 27U;
    value *= UINT64_C(0x94d049bb133111eb);
    value ^= value >> 31U;
    return value;
}

static void map_init_with_capacity(StateMap *map, MemoryBudget *budget,
                                   size_t capacity)
{
    if (capacity < INITIAL_CAPACITY ||
        (capacity & (capacity - 1U)) != 0U) {
        die("internal non-power-of-two DP capacity");
    }
    map->capacity = capacity;
    map->size = 0;
    map->budget = budget;
    map->slots = allocate_slots(budget, capacity);
}

static void map_init(StateMap *map, MemoryBudget *budget)
{
    map_init_with_capacity(map, budget, INITIAL_CAPACITY);
}

static void map_destroy(StateMap *map)
{
    if (map->slots != NULL) {
        free_slots(map->budget, map->slots, map->capacity);
    }
    map->slots = NULL;
    map->capacity = 0;
    map->size = 0;
}

static StateSlot *map_find_slot(StateMap *map, uint64_t key_plus_one)
{
    size_t index = (size_t)mix_key(key_plus_one) & (map->capacity - 1U);
    for (;;) {
        StateSlot *slot = &map->slots[index];
        if (slot->key_plus_one == 0 ||
            slot->key_plus_one == key_plus_one) {
            return slot;
        }
        index = (index + 1U) & (map->capacity - 1U);
    }
}

static const StateSlot *map_find_const(const StateMap *map,
                                       uint64_t key_plus_one)
{
    size_t index = (size_t)mix_key(key_plus_one) & (map->capacity - 1U);
    for (;;) {
        const StateSlot *slot = &map->slots[index];
        if (slot->key_plus_one == 0 ||
            slot->key_plus_one == key_plus_one) {
            return slot;
        }
        index = (index + 1U) & (map->capacity - 1U);
    }
}

static void map_grow(StateMap *map)
{
    if (map->capacity > SIZE_MAX / 2U) {
        die("DP hash-table capacity overflow");
    }
    size_t old_capacity = map->capacity;
    StateSlot *old_slots = map->slots;
    size_t new_capacity = old_capacity * 2U;
    StateSlot *new_slots = allocate_slots(map->budget, new_capacity);

    map->capacity = new_capacity;
    map->slots = new_slots;
    for (size_t i = 0; i < old_capacity; ++i) {
        if (old_slots[i].key_plus_one != 0) {
            StateSlot *destination =
                map_find_slot(map, old_slots[i].key_plus_one);
            *destination = old_slots[i];
        }
    }
    free_slots(map->budget, old_slots, old_capacity);
}

static void map_add(StateMap *map, uint64_t packed_key, Count128 addend)
{
    if (packed_key == UINT64_MAX) {
        die("packed state key overflow");
    }
    uint64_t key_plus_one = packed_key + UINT64_C(1);
    StateSlot *slot = map_find_slot(map, key_plus_one);
    if (slot->key_plus_one != 0) {
        count_add_to(&slot->count, addend);
        return;
    }

    if (map->size + 1U >
        (map->capacity / LOAD_DENOMINATOR) * LOAD_NUMERATOR) {
        map_grow(map);
        slot = map_find_slot(map, key_plus_one);
        if (slot->key_plus_one != 0) {
            die("internal duplicate state after table growth");
        }
    }
    slot->key_plus_one = key_plus_one;
    slot->count = addend;
    ++map->size;
}

static void map_clear(StateMap *map)
{
    size_t bytes = checked_product_size(map->capacity, sizeof(StateSlot));
    memset(map->slots, 0, bytes);
    map->size = 0;
}

/*
 * next contains an obsolete layer.  Releasing it before reserving a likely
 * final capacity avoids the old+new transient allocation of map_grow near
 * the middle.  A later grow remains available if the estimate is low.
 */
static void map_prepare_next(StateMap *next, size_t desired_capacity)
{
    if (desired_capacity < INITIAL_CAPACITY) {
        desired_capacity = INITIAL_CAPACITY;
    }
    if ((desired_capacity & (desired_capacity - 1U)) != 0U) {
        die("internal non-power-of-two reserve capacity");
    }
    if (next->capacity == desired_capacity) {
        map_clear(next);
        return;
    }
    MemoryBudget *budget = next->budget;
    map_destroy(next);
    map_init_with_capacity(next, budget, desired_capacity);
}

static uint64_t reverse_bits_64(uint64_t value)
{
    value = ((value & UINT64_C(0x5555555555555555)) << 1U) |
            ((value >> 1U) & UINT64_C(0x5555555555555555));
    value = ((value & UINT64_C(0x3333333333333333)) << 2U) |
            ((value >> 2U) & UINT64_C(0x3333333333333333));
    value = ((value & UINT64_C(0x0f0f0f0f0f0f0f0f)) << 4U) |
            ((value >> 4U) & UINT64_C(0x0f0f0f0f0f0f0f0f));
    value = ((value & UINT64_C(0x00ff00ff00ff00ff)) << 8U) |
            ((value >> 8U) & UINT64_C(0x00ff00ff00ff00ff));
    value = ((value & UINT64_C(0x0000ffff0000ffff)) << 16U) |
            ((value >> 16U) & UINT64_C(0x0000ffff0000ffff));
    return (value << 32U) | (value >> 32U);
}

static uint64_t reverse_low_bits(uint64_t mask, int n)
{
    return reverse_bits_64(mask) >> (64U - (unsigned)n);
}

static uint64_t pack_state(uint64_t used, unsigned a, unsigned b)
{
    return (used << STATE_SHIFT) |
           ((uint64_t)a << ENDPOINT_BITS) | (uint64_t)b;
}

static void unpack_state(uint64_t packed, uint64_t *used,
                         unsigned *a, unsigned *b)
{
    *b = (unsigned)(packed & ENDPOINT_MASK);
    *a = (unsigned)((packed >> ENDPOINT_BITS) & ENDPOINT_MASK);
    *used = packed >> STATE_SHIFT;
}

static uint64_t canonical_state(uint64_t used, unsigned a, unsigned b,
                                int n, bool use_symmetry)
{
    uint64_t original = pack_state(used, a, b);
    if (!use_symmetry) {
        return original;
    }
    uint64_t complemented = pack_state(
        reverse_low_bits(used, n),
        (unsigned)(n - 1 - (int)a),
        (unsigned)(n - 1 - (int)b));
    return original < complemented ? original : complemented;
}

static Count128 prefix_lookup(const StateMap *map, uint64_t used,
                              unsigned a, unsigned b, int n,
                              bool use_symmetry)
{
    uint64_t key = canonical_state(used, a, b, n, use_symmetry);
    const StateSlot *slot = map_find_const(map, key + UINT64_C(1));
    if (slot->key_plus_one == 0) {
        return count_zero();
    }
    return use_symmetry ? count_halve(slot->count) : slot->count;
}

static void make_masks(int n, uint64_t *bad,
                       uint64_t allowed[MAX_SUPPORTED_N][MAX_SUPPORTED_N])
{
    uint64_t full = (UINT64_C(1) << (unsigned)n) - UINT64_C(1);
    for (int value = 0; value < n; ++value) {
        bad[value] = 0;
        for (int other = 0; other < n; ++other) {
            int difference = value - other;
            if (difference > -3 && difference < 3) {
                bad[value] |= UINT64_C(1) << (unsigned)other;
            }
        }
    }
    for (int a = 0; a < n; ++a) {
        for (int b = 0; b < n; ++b) {
            allowed[a][b] = full & ~(bad[a] | bad[b]);
        }
    }
}

static void initialize_pairs(StateMap *map, int n, bool use_symmetry)
{
    Count128 one = count_from_u64(UINT64_C(1));
    for (int a = 0; a < n; ++a) {
        for (int b = 0; b < n; ++b) {
            int difference = a - b;
            if (difference > -3 && difference < 3) {
                continue;
            }
            uint64_t used = (UINT64_C(1) << (unsigned)a) |
                            (UINT64_C(1) << (unsigned)b);
            uint64_t key = canonical_state(used, (unsigned)a,
                                           (unsigned)b, n,
                                           use_symmetry);
            map_add(map, key, one);
        }
    }
}

static void extend_layer(const StateMap *current, StateMap *next,
                         int n, const uint64_t allowed[MAX_SUPPORTED_N]
                                                        [MAX_SUPPORTED_N],
                         bool use_symmetry, MitmStats *stats)
{
    for (size_t index = 0; index < current->capacity; ++index) {
        const StateSlot *slot = &current->slots[index];
        if (slot->key_plus_one == 0) {
            continue;
        }
        uint64_t used;
        unsigned a;
        unsigned b;
        unpack_state(slot->key_plus_one - UINT64_C(1), &used, &a, &b);
        uint64_t candidates = allowed[a][b] & ~used;
        while (candidates != 0) {
            uint64_t bit = candidates & (UINT64_C(0) - candidates);
            candidates ^= bit;
#if defined(__GNUC__) || defined(__clang__)
            unsigned c = (unsigned)__builtin_ctzll(bit);
#else
            unsigned c = 0;
            while ((bit >> c) != UINT64_C(1)) {
                ++c;
            }
#endif
            uint64_t key = canonical_state(used | bit, b, c, n,
                                           use_symmetry);
            map_add(next, key, slot->count);
            if (stats->prefix_transitions == UINT64_MAX) {
                die("prefix transition counter overflow");
            }
            ++stats->prefix_transitions;
        }
    }
}

static uint64_t first_mask_with_popcount(int count)
{
    return (UINT64_C(1) << (unsigned)count) - UINT64_C(1);
}

static uint64_t next_fixed_popcount_mask(uint64_t mask)
{
    if (mask == 0) {
        die("internal zero mask in fixed-popcount iterator");
    }
    uint64_t low_bit = mask & (UINT64_C(0) - mask);
    if (low_bit == 0) {
        die("internal low-bit failure in fixed-popcount iterator");
    }
    uint64_t ripple = mask + low_bit;
    return ripple | (((ripple ^ mask) >> 2U) / low_bit);
}

static bool difference_is_allowed(unsigned left, unsigned right)
{
    int difference = (int)left - (int)right;
    return difference <= -3 || difference >= 3;
}

static Count128 join_halves(const StateMap *left_map,
                            const StateMap *right_map,
                            int n, int left_length,
                            const uint64_t *bad,
                            bool use_symmetry, MitmStats *stats)
{
    uint64_t full = (UINT64_C(1) << (unsigned)n) - UINT64_C(1);
    uint64_t subset = first_mask_with_popcount(left_length);
    uint64_t limit = UINT64_C(1) << (unsigned)n;
    bool equal_halves = left_length * 2 == n;
    Count128 total = count_zero();

    Count128 right_matrix[MAX_SUPPORTED_N][MAX_SUPPORTED_N];
    Count128 right_row[MAX_SUPPORTED_N];
    Count128 q[MAX_SUPPORTED_N];

    while (subset < limit) {
        uint64_t complement = full ^ subset;
        if (!equal_halves || subset < complement) {
            if (stats->split_subsets == UINT64_MAX) {
                die("split-subset counter overflow");
            }
            ++stats->split_subsets;

            uint64_t c_bits = complement;
            while (c_bits != 0) {
                uint64_t c_bit = c_bits & (UINT64_C(0) - c_bits);
                c_bits ^= c_bit;
                unsigned c = (unsigned)__builtin_ctzll(c_bit);
                right_row[c] = count_zero();

                uint64_t d_bits = complement;
                while (d_bits != 0) {
                    uint64_t d_bit = d_bits & (UINT64_C(0) - d_bits);
                    d_bits ^= d_bit;
                    unsigned d = (unsigned)__builtin_ctzll(d_bit);
                    if (!difference_is_allowed(c, d)) {
                        continue;
                    }
                    /* Right half begins c,d, hence its reverse ends d,c. */
                    Count128 value = prefix_lookup(
                        right_map, complement, d, c, n, use_symmetry);
                    right_matrix[c][d] = value;
                    count_add_to(&right_row[c], value);
                }
            }

            uint64_t b_bits = subset;
            while (b_bits != 0) {
                uint64_t b_bit = b_bits & (UINT64_C(0) - b_bits);
                b_bits ^= b_bit;
                unsigned b = (unsigned)__builtin_ctzll(b_bit);
                Count128 q_total = count_zero();

                c_bits = complement;
                while (c_bits != 0) {
                    uint64_t c_bit = c_bits & (UINT64_C(0) - c_bits);
                    c_bits ^= c_bit;
                    unsigned c = (unsigned)__builtin_ctzll(c_bit);
                    Count128 excluded_d = count_zero();
                    uint64_t d_bits = bad[b] & complement;
                    while (d_bits != 0) {
                        uint64_t d_bit =
                            d_bits & (UINT64_C(0) - d_bits);
                        d_bits ^= d_bit;
                        unsigned d = (unsigned)__builtin_ctzll(d_bit);
                        if (difference_is_allowed(c, d)) {
                            count_add_to(&excluded_d,
                                         right_matrix[c][d]);
                        }
                    }
                    q[c] = count_subtract(right_row[c], excluded_d);
                    count_add_to(&q_total, q[c]);
                }

                uint64_t a_bits = subset;
                while (a_bits != 0) {
                    uint64_t a_bit = a_bits & (UINT64_C(0) - a_bits);
                    a_bits ^= a_bit;
                    unsigned a = (unsigned)__builtin_ctzll(a_bit);
                    if (!difference_is_allowed(a, b)) {
                        continue;
                    }
                    Count128 left = prefix_lookup(
                        left_map, subset, a, b, n, use_symmetry);
                    if (count_is_zero(left)) {
                        continue;
                    }

                    Count128 excluded_c = count_zero();
                    uint64_t excluded_bits =
                        (bad[a] | bad[b]) & complement;
                    while (excluded_bits != 0) {
                        uint64_t c_bit =
                            excluded_bits &
                            (UINT64_C(0) - excluded_bits);
                        excluded_bits ^= c_bit;
                        unsigned c = (unsigned)__builtin_ctzll(c_bit);
                        count_add_to(&excluded_c, q[c]);
                    }
                    Count128 compatible_right =
                        count_subtract(q_total, excluded_c);
                    if (!count_is_zero(compatible_right)) {
                        Count128 product =
                            count_multiply(left, compatible_right);
                        count_add_to(&total, product);
                        if (stats->joined_endpoint_pairs == UINT64_MAX) {
                            die("joined endpoint-pair counter overflow");
                        }
                        ++stats->joined_endpoint_pairs;
                    }
                }
            }
        }

        uint64_t next = next_fixed_popcount_mask(subset);
        if (next <= subset || next >= limit) {
            break;
        }
        subset = next;
    }

    if (equal_halves) {
        count_add_to(&total, total);
    }
    return total;
}

static bool permutation_is_valid(const int *permutation, int n)
{
    for (int i = 0; i < n; ++i) {
        if (i + 1 < n) {
            int difference = permutation[i + 1] - permutation[i];
            if (difference > -3 && difference < 3) {
                return false;
            }
        }
        if (i + 2 < n) {
            int difference = permutation[i + 2] - permutation[i];
            if (difference > -3 && difference < 3) {
                return false;
            }
        }
    }
    return true;
}

static bool next_permutation(int *permutation, int n)
{
    int i = n - 2;
    while (i >= 0 && permutation[i] >= permutation[i + 1]) {
        --i;
    }
    if (i < 0) {
        return false;
    }
    int j = n - 1;
    while (permutation[j] <= permutation[i]) {
        --j;
    }
    int temporary = permutation[i];
    permutation[i] = permutation[j];
    permutation[j] = temporary;
    for (int left = i + 1, right = n - 1; left < right;
         ++left, --right) {
        temporary = permutation[left];
        permutation[left] = permutation[right];
        permutation[right] = temporary;
    }
    return true;
}

static Count128 direct_count(int n)
{
    if (n == 0) {
        return count_from_u64(UINT64_C(1));
    }
    int permutation[DIRECT_CHECK_MAX_N];
    for (int i = 0; i < n; ++i) {
        permutation[i] = i;
    }
    Count128 result = count_zero();
    do {
        if (permutation_is_valid(permutation, n)) {
            count_add_to(&result, count_from_u64(UINT64_C(1)));
        }
    } while (next_permutation(permutation, n));
    return result;
}

static void verify_reference(Count128 value, int n)
{
    if (n <= REFERENCE_MAX_N) {
        Count128 expected = parse_count(reference_terms[n]);
        if (!count_equal(value, expected)) {
            fprintf(stderr, "error: A279214 mismatch at n=%d: got ", n);
            (void)fprint_count(stderr, value);
            fprintf(stderr, ", expected %s\n", reference_terms[n]);
            exit(EXIT_FAILURE);
        }
    }
    if (n > 1 && (value.low & UINT64_C(1)) != 0) {
        fprintf(stderr, "error: parity check failed at n=%d\n", n);
        exit(EXIT_FAILURE);
    }
}

static Count128 compute_mitm(int n, bool use_symmetry,
                             uint64_t memory_mib, MitmStats *stats)
{
    double started = monotonic_seconds();
    memset(stats, 0, sizeof(*stats));
    if (n <= 3) {
        Count128 result = direct_count(n);
        stats->total_seconds = monotonic_seconds() - started;
        return result;
    }

    int left_length = n / 2;
    int right_length = n - left_length;
    uint64_t bad[MAX_SUPPORTED_N] = {0};
    uint64_t allowed[MAX_SUPPORTED_N][MAX_SUPPORTED_N] = {{0}};
    make_masks(n, bad, allowed);

    MemoryBudget budget;
    budget.limit = checked_product_size((size_t)memory_mib,
                                        (size_t)UINT64_C(1048576));
    budget.in_use = 0;
    budget.peak = 0;

    StateMap current;
    StateMap next;
    map_init(&current, &budget);
    map_init(&next, &budget);
    initialize_pairs(&current, n, use_symmetry);

    double build_started = monotonic_seconds();
    for (int length = 2;
         length < right_length && current.size != 0U; ++length) {
        size_t desired = current.capacity;
        if (desired <= SIZE_MAX / 2U) {
            desired *= 2U;
        }
        map_prepare_next(&next, desired);
        extend_layer(&current, &next, n, allowed,
                     use_symmetry, stats);
        StateMap temporary = current;
        current = next;
        next = temporary;
    }
    stats->build_seconds = monotonic_seconds() - build_started;
    stats->peak_bytes = budget.peak;

    const StateMap *left_map;
    const StateMap *right_map;
    if (left_length == right_length) {
        left_map = &current;
        right_map = &current;
        stats->left_states = current.size;
        stats->right_states = current.size;
        map_destroy(&next);
    } else {
        /* Last swap left the length-m layer in next and length-r in current. */
        left_map = &next;
        right_map = &current;
        stats->left_states = next.size;
        stats->right_states = current.size;
    }

    double join_started = monotonic_seconds();
    Count128 result = join_halves(left_map, right_map, n, left_length,
                                  bad, use_symmetry, stats);
    stats->join_seconds = monotonic_seconds() - join_started;

    map_destroy(&current);
    map_destroy(&next);
    if (budget.in_use != 0U) {
        die("internal DP memory leak");
    }
    stats->total_seconds = monotonic_seconds() - started;
    return result;
}

static Count128 compute_value(int n, bool use_symmetry,
                              uint64_t memory_mib, bool verbose)
{
    MitmStats stats;
    Count128 value = compute_mitm(n, use_symmetry, memory_mib, &stats);
    verify_reference(value, n);
    if (verbose) {
        fprintf(stderr,
                "279214_02: n=%d, MITM %s, left/right states=%zu/%zu, "
                "prefix transitions=%" PRIu64 ", split subsets=%" PRIu64
                ", joined endpoint pairs=%" PRIu64
                ", peak table memory=%.1f MiB, build/join/total="
                "%.3f/%.3f/%.3f s\n",
                n, use_symmetry ? "complement-quotient" : "plain",
                stats.left_states, stats.right_states,
                stats.prefix_transitions, stats.split_subsets,
                stats.joined_endpoint_pairs,
                (double)stats.peak_bytes / 1048576.0,
                stats.build_seconds, stats.join_seconds,
                stats.total_seconds);
    }
    return value;
}

static int check_implementation(int maximum_n, uint64_t memory_mib)
{
    if (maximum_n > REFERENCE_MAX_N) {
        fprintf(stderr, "error: CHECK_N must be in 0..%d: %d\n",
                REFERENCE_MAX_N, maximum_n);
        return EXIT_FAILURE;
    }
    for (int n = 0; n <= maximum_n; ++n) {
        Count128 quotient = compute_value(n, true, memory_mib, false);
        if (n <= SYMMETRY_CHECK_MAX_N) {
            Count128 plain = compute_value(n, false, memory_mib, false);
            if (!count_equal(quotient, plain)) {
                fprintf(stderr,
                        "error: MITM symmetry/plain mismatch at n=%d: ", n);
                (void)fprint_count(stderr, quotient);
                fputs(" versus ", stderr);
                (void)fprint_count(stderr, plain);
                fputc('\n', stderr);
                return EXIT_FAILURE;
            }
        }
        if (n <= DIRECT_CHECK_MAX_N) {
            Count128 direct = direct_count(n);
            if (!count_equal(quotient, direct)) {
                fprintf(stderr,
                        "error: MITM/direct-permutation mismatch at n=%d: ",
                        n);
                (void)fprint_count(stderr, quotient);
                fputs(" versus ", stderr);
                (void)fprint_count(stderr, direct);
                fputc('\n', stderr);
                return EXIT_FAILURE;
            }
        }
    }
    printf("ok: MITM agrees with OEIS through n=%d and 279214_01 "
           "regression terms through n=%d; independent full-permutation "
           "scan through n=%d; symmetry/plain MITM through n=%d\n",
           maximum_n < OEIS_MAX_N ? maximum_n : OEIS_MAX_N,
           maximum_n,
           maximum_n < DIRECT_CHECK_MAX_N
               ? maximum_n : DIRECT_CHECK_MAX_N,
           maximum_n < SYMMETRY_CHECK_MAX_N
               ? maximum_n : SYMMETRY_CHECK_MAX_N);
    return EXIT_SUCCESS;
}

static char *path_beside_executable(const char *argv0,
                                    const char *filename)
{
    char executable[PATH_MAX];
    char resolved[PATH_MAX];
    bool found = false;
#ifdef __APPLE__
    uint32_t size = (uint32_t)sizeof(executable);
    if (_NSGetExecutablePath(executable, &size) == 0) {
        found = true;
    }
#elif defined(__linux__)
    ssize_t length = readlink("/proc/self/exe", executable,
                              sizeof(executable) - 1U);
    if (length >= 0) {
        executable[length] = '\0';
        found = true;
    }
#endif
    if (!found) {
        size_t length = strlen(argv0);
        if (length >= sizeof(executable)) {
            die("executable path is too long");
        }
        memcpy(executable, argv0, length + 1U);
    }
    const char *base = realpath(executable, resolved);
    if (base == NULL) {
        base = executable;
    }
    const char *slash = strrchr(base, '/');
    size_t directory_length =
        slash == NULL ? 1U : (size_t)(slash - base);
    if (slash != NULL && directory_length == 0U) {
        directory_length = 1U;
    }
    size_t filename_length = strlen(filename);
    if (directory_length > SIZE_MAX - filename_length - 2U) {
        die("output path length overflow");
    }
    char *path = malloc(directory_length + filename_length + 2U);
    if (path == NULL) {
        die("out of memory while making output path");
    }
    if (slash == NULL) {
        path[0] = '.';
    } else if (slash == base) {
        path[0] = '/';
    } else {
        memcpy(path, base, directory_length);
    }
    path[directory_length] = '/';
    memcpy(path + directory_length + 1U, filename,
           filename_length + 1U);
    return path;
}

static void produce_file(const char *argv0, int maximum_n,
                         bool use_symmetry, uint64_t memory_mib)
{
    char *final_path =
        path_beside_executable(argv0, "b279214_02.txt");
    char *part_path =
        path_beside_executable(argv0, "b279214_02_part.txt");
    FILE *stream = fopen(part_path, "w");
    if (stream == NULL) {
        fprintf(stderr, "error: cannot open %s: %s\n",
                part_path, strerror(errno));
        free(final_path);
        free(part_path);
        exit(EXIT_FAILURE);
    }
    for (int n = SEQUENCE_OFFSET; n <= maximum_n; ++n) {
        Count128 value = compute_value(n, use_symmetry,
                                       memory_mib, true);
        if (fprintf(stream, "%d ", n) < 0 ||
            fprint_count(stream, value) != 0 ||
            fputc('\n', stream) == EOF || fflush(stream) != 0) {
            (void)fclose(stream);
            free(final_path);
            free(part_path);
            die("could not write the A279214 MITM output file");
        }
    }
    if (fclose(stream) != 0) {
        free(final_path);
        free(part_path);
        die("could not close the A279214 MITM output file");
    }
    if (rename(part_path, final_path) != 0) {
        fprintf(stderr, "error: cannot rename %s to %s: %s\n",
                part_path, final_path, strerror(errno));
        free(final_path);
        free(part_path);
        exit(EXIT_FAILURE);
    }
    printf("wrote %s (n=%d..%d)\n",
           final_path, SEQUENCE_OFFSET, maximum_n);
    free(final_path);
    free(part_path);
}

static void usage(const char *program)
{
    fprintf(stderr,
            "usage: %s [MAX_N] [--memory-mib M] [--no-symmetry]\n"
            "       %s --upto MAX_N [--memory-mib M] [--no-symmetry]\n"
            "       %s --term N [--memory-mib M] [--no-symmetry]\n"
            "       %s --check [MAX_N] [--memory-mib M]\n"
            "\n"
            "N and MAX_N may be %d..%d; 128-bit result arithmetic is "
            "proved safe throughout.\n"
            "The default is --upto %d with a %" PRIu64
            " MiB DP-table budget.\n"
            "A range run writes b279214_02.txt beside the executable.\n"
            "--no-symmetry is slower and is mainly a diagnostic.\n",
            program, program, program, program,
            SEQUENCE_OFFSET, MAX_SUPPORTED_N, DEFAULT_MAX_N,
            DEFAULT_MEMORY_MIB);
}

int main(int argc, char **argv)
{
    if (argc == 2 &&
        (strcmp(argv[1], "--help") == 0 ||
         strcmp(argv[1], "-h") == 0)) {
        usage(argv[0]);
        return EXIT_SUCCESS;
    }

    RunMode mode = RUN_UPTO;
    int n = -1;
    bool have_n = false;
    bool have_mode = false;
    bool use_symmetry = true;
    bool have_symmetry_option = false;
    uint64_t memory_mib = DEFAULT_MEMORY_MIB;
    bool have_memory = false;

    for (int argument = 1; argument < argc; ++argument) {
        const char *text = argv[argument];
        if (strcmp(text, "--memory-mib") == 0) {
            if (have_memory || argument + 1 >= argc) {
                usage(argv[0]);
                return EXIT_FAILURE;
            }
            memory_mib = parse_memory_mib(argv[++argument]);
            have_memory = true;
        } else if (strcmp(text, "--no-symmetry") == 0) {
            if (have_symmetry_option) {
                usage(argv[0]);
                return EXIT_FAILURE;
            }
            use_symmetry = false;
            have_symmetry_option = true;
        } else if (strcmp(text, "--term") == 0 ||
                   strcmp(text, "--upto") == 0) {
            if (have_mode || have_n || argument + 1 >= argc) {
                usage(argv[0]);
                return EXIT_FAILURE;
            }
            mode = strcmp(text, "--term") == 0 ? RUN_TERM : RUN_UPTO;
            have_mode = true;
            n = parse_n(argv[++argument],
                        mode == RUN_TERM ? "N" : "MAX_N");
            have_n = true;
        } else if (strcmp(text, "--check") == 0) {
            if (have_mode || have_n) {
                usage(argv[0]);
                return EXIT_FAILURE;
            }
            mode = RUN_CHECK;
            have_mode = true;
            if (argument + 1 < argc && argv[argument + 1][0] != '-') {
                n = parse_n(argv[++argument], "CHECK_N");
                have_n = true;
            }
        } else if (text[0] == '-' || have_n) {
            usage(argv[0]);
            return EXIT_FAILURE;
        } else {
            n = parse_n(text,
                        mode == RUN_CHECK ? "CHECK_N" : "MAX_N");
            have_n = true;
        }
    }

    if (!have_n) {
        n = mode == RUN_CHECK ? DEFAULT_CHECK_N : DEFAULT_MAX_N;
    }
    if (mode == RUN_CHECK) {
        return check_implementation(n, memory_mib);
    }
    if (mode == RUN_TERM) {
        Count128 value = compute_value(n, use_symmetry,
                                       memory_mib, true);
        printf("%d ", n);
        if (fprint_count(stdout, value) != 0 || fputc('\n', stdout) == EOF) {
            die("could not write result");
        }
        return EXIT_SUCCESS;
    }
    produce_file(argv[0], n, use_symmetry, memory_mib);
    return EXIT_SUCCESS;
}
