/*
 * A278339: set partitions of [n] into blocks with distinct square sums.
 *
 * Parallel exact-cover DP.  A state is (M,U), where M is the remaining
 * element mask and U records square sums already used.  The block containing
 * max(M) is removed next, so every set partition is counted exactly once.
 * Candidate blocks are generated by meet-in-the-middle subset sum.
 *
 * Root blocks are distributed through a pthread work queue.  All workers use
 * one concurrent open-addressed memo table.  An atomic busy tag makes every
 * complete (M,U) state evaluate once; recursive popcount strictly decreases,
 * so waits cannot form a cycle.  Full keys resolve hash collisions.
 *
 * The memo table is fixed during each term.  With --upto it grows only between
 * consecutive n, when no worker exists.  Entries are retained through n=24;
 * from n=25 onward each term gets a fresh n-sized table, preventing unrelated
 * used-square states from accumulating into a multi-GiB table.  A precomputed
 * reachability table rejects a square choice unless the remaining sum is a
 * subset sum of the remaining unused squares.
 * Known terms are consulted only by --self-test after computation.
 *
 * Build:
 *   clang -O3 -march=native -std=c11 -Wall -Wextra -Wpedantic \
 *       278339_02.c -o 278339_02 -pthread
 *
 * Example:
 *   ./278339_02 --upto 29 --threads 8 --self-test --stats
 *
 * Every completed term is flushed and fsync'ed to b278339_02.txt.
 */

#include <errno.h>
#include <inttypes.h>
#include <pthread.h>
#include <sched.h>
#include <stdbool.h>
#include <stdatomic.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>

#define MAX_N 29U
#define DEFAULT_N 24U
#define KNOWN_N 29U
#define MITM_MIN_REST_SIZE 8U
#define PARALLEL_MIN_N 18U
#define PROGRESS_MIN_N 24U
#define TASK_CHUNK 64U
#define PROGRESS_INTERVAL_SECONDS 60.0
#define PROGRESS_POLL_NANOSECONDS 100000000L
#define LOW_BITS 16U
#define LOW_SIZE (UINT32_C(1) << LOW_BITS)
#define HIGH_BITS (MAX_N - LOW_BITS)
#define HIGH_SIZE (UINT32_C(1) << HIGH_BITS)
#define MAX_SUM (MAX_N * (MAX_N + 1U) / 2U)
#define MAX_ROOT 20U
#define SQUARE_MASK_COUNT (UINT32_C(1) << MAX_ROOT)
#define REACH_WORDS ((MAX_SUM + 64U) / 64U)
#define BFILE_NAME "b278339_02.txt"

typedef struct {
    _Atomic uint64_t *tags;
    uint64_t *values;
    size_t capacity;
    _Atomic size_t size;
} ConcurrentMemo;

typedef struct {
    ConcurrentMemo memo;
    _Atomic uint64_t computed_states;
    _Atomic uint64_t nonzero_states;
    _Atomic uint64_t pruned_states;
    _Atomic uint64_t wait_count;
    unsigned thread_count;
    unsigned n;
    uint64_t *reachable;
    uint16_t low_sum[LOW_SIZE];
    uint16_t high_sum[HIGH_SIZE];
    uint32_t square_bit[MAX_SUM + 1U];
    uint8_t ceil_root[MAX_SUM + 1U];
} Shared;

typedef struct {
    Shared *shared;
    uint32_t *mitm_grouped[MAX_N];
    size_t mitm_capacity[MAX_N];
} Worker;

typedef struct {
    size_t index;
} MemoToken;

typedef struct {
    uint32_t block_rest;
    uint32_t square_mask;
} RootTask;

static const uint64_t known[KNOWN_N + 1U] = {
    UINT64_C(1), UINT64_C(1), UINT64_C(0), UINT64_C(0),
    UINT64_C(1), UINT64_C(0), UINT64_C(1), UINT64_C(0),
    UINT64_C(1), UINT64_C(23), UINT64_C(9), UINT64_C(41),
    UINT64_C(248), UINT64_C(277), UINT64_C(1556), UINT64_C(2854),
    UINT64_C(5233), UINT64_C(20701), UINT64_C(145137),
    UINT64_C(1626890), UINT64_C(4118910), UINT64_C(9963276),
    UINT64_C(9260756), UINT64_C(64027363), UINT64_C(365237571),
    UINT64_C(1002679107), UINT64_C(21594036300),
    UINT64_C(24465529531), UINT64_C(144914973347),
    UINT64_C(1921444799766)
};

static _Noreturn void die(const char *message)
{
    fprintf(stderr, "error: %s\n", message);
    exit(EXIT_FAILURE);
}

static unsigned parse_n(const char *text)
{
    errno = 0;
    char *end = NULL;
    const uintmax_t value = strtoumax(text, &end, 10);
    if (errno != 0 || end == text || *end != '\0' || value > MAX_N) {
        fprintf(stderr, "error: n must be in 0..%u: %s\n", MAX_N, text);
        exit(EXIT_FAILURE);
    }
    return (unsigned)value;
}

static unsigned parse_threads(const char *text)
{
    errno = 0;
    char *end = NULL;
    const uintmax_t value = strtoumax(text, &end, 10);
    if (errno != 0 || end == text || *end != '\0' ||
        value == 0 || value > 64U) {
        fprintf(stderr, "error: threads must be in 1..64: %s\n", text);
        exit(EXIT_FAILURE);
    }
    return (unsigned)value;
}

static unsigned default_thread_count(void)
{
    const long detected = sysconf(_SC_NPROCESSORS_ONLN);
    if (detected <= 0) return 1U;
    return detected > 8 ? 8U : (unsigned)detected;
}

static unsigned highest_bit_index(uint32_t mask)
{
#if defined(__clang__) || defined(__GNUC__)
    return 31U - (unsigned)__builtin_clz(mask);
#else
    unsigned index = 0;
    while (mask >>= 1U) ++index;
    return index;
#endif
}

static unsigned bit_count(uint32_t mask)
{
#if defined(__clang__) || defined(__GNUC__)
    return (unsigned)__builtin_popcount(mask);
#else
    unsigned count = 0;
    while (mask != 0) {
        mask &= mask - 1U;
        ++count;
    }
    return count;
#endif
}

static double monotonic_seconds(void)
{
    struct timespec now;
    if (clock_gettime(CLOCK_MONOTONIC, &now) != 0)
        die("could not read the monotonic clock");
    return (double)now.tv_sec + (double)now.tv_nsec / 1000000000.0;
}

static uint16_t subset_sum(const Shared *shared, uint32_t mask)
{
    return (uint16_t)(shared->low_sum[mask & (LOW_SIZE - 1U)] +
                      shared->high_sum[mask >> LOW_BITS]);
}

static uint64_t hash_key(uint64_t key)
{
    key ^= key >> 30U;
    key *= UINT64_C(0xbf58476d1ce4e5b9);
    key ^= key >> 27U;
    key *= UINT64_C(0x94d049bb133111eb);
    key ^= key >> 31U;
    return key;
}

static uint64_t state_key(uint32_t mask, uint32_t used_squares)
{
    return (((uint64_t)used_squares << MAX_N) | mask) + 1U;
}

static bool memo_claim(Shared *shared, uint64_t key, uint64_t *value,
                       MemoToken *token)
{
    ConcurrentMemo *memo = &shared->memo;
    const uint64_t complete_tag = key << 1U;
    const uint64_t busy_tag = complete_tag | UINT64_C(1);
    size_t index = (size_t)hash_key(key) & (memo->capacity - 1U);
    for (size_t probes = 0; probes < memo->capacity; ++probes) {
        uint64_t tag = atomic_load_explicit(&memo->tags[index],
                                            memory_order_acquire);
        if (tag == complete_tag) {
            *value = memo->values[index];
            return false;
        }
        if (tag == busy_tag) {
            atomic_fetch_add_explicit(&shared->wait_count, 1,
                                      memory_order_relaxed);
            unsigned spins = 0;
            do {
                tag = atomic_load_explicit(&memo->tags[index],
                                           memory_order_acquire);
                if (++spins == 1024U && tag == busy_tag) {
                    sched_yield();
                    spins = 0;
                }
            } while (tag == busy_tag);
            if (tag == complete_tag) {
                *value = memo->values[index];
                return false;
            }
            continue;
        }
        if (tag == 0) {
            uint64_t expected = 0;
            if (atomic_compare_exchange_weak_explicit(
                    &memo->tags[index], &expected, busy_tag,
                    memory_order_acq_rel, memory_order_acquire)) {
                const size_t size =
                    atomic_fetch_add_explicit(&memo->size, 1,
                                              memory_order_relaxed) + 1U;
                if (size * 10U >= memo->capacity * 7U)
                    die("concurrent memo table exceeded 70% load");
                token->index = index;
                return true;
            }
            continue;
        }
        index = (index + 1U) & (memo->capacity - 1U);
    }
    die("concurrent memo table is full");
}

static void memo_publish(Shared *shared, uint64_t key,
                         const MemoToken *token, uint64_t value)
{
    shared->memo.values[token->index] = value;
    atomic_store_explicit(&shared->memo.tags[token->index], key << 1U,
                          memory_order_release);
    atomic_fetch_add_explicit(&shared->computed_states, 1,
                              memory_order_relaxed);
    if (value != 0)
        atomic_fetch_add_explicit(&shared->nonzero_states, 1,
                                  memory_order_relaxed);
}

static bool unused_squares_can_sum(const Shared *shared,
                                   uint32_t used_squares, unsigned sum)
{
    const size_t offset = (size_t)used_squares * REACH_WORDS;
    return ((shared->reachable[offset + sum / 64U] >> (sum % 64U)) &
            UINT64_C(1)) != 0;
}

static bool square_choice_can_finish(const Shared *shared,
                                     uint32_t used_squares,
                                     uint32_t square_mask,
                                     unsigned remaining_sum,
                                     unsigned square)
{
    return square_mask != 0 && (used_squares & square_mask) == 0 &&
           square <= remaining_sum &&
           unused_squares_can_sum(shared, used_squares | square_mask,
                                  remaining_sum - square);
}

static uint32_t *mitm_workspace(Worker *worker, unsigned depth,
                                size_t needed)
{
    if (depth >= MAX_N) die("internal recursion depth overflow");
    if (worker->mitm_capacity[depth] < needed) {
        if (needed > SIZE_MAX / sizeof(*worker->mitm_grouped[depth]))
            die("meet-in-the-middle workspace is too large");
        uint32_t *replacement =
            realloc(worker->mitm_grouped[depth],
                    needed * sizeof(*worker->mitm_grouped[depth]));
        if (replacement == NULL)
            die("could not allocate meet-in-the-middle workspace");
        worker->mitm_grouped[depth] = replacement;
        worker->mitm_capacity[depth] = needed;
    }
    return worker->mitm_grouped[depth];
}

static void checked_add(uint64_t *total, uint64_t addend)
{
    if (UINT64_MAX - *total < addend)
        die("uint64_t overflow while counting partitions");
    *total += addend;
}

static uint64_t count_partitions(Worker *worker, uint32_t mask,
                                 uint32_t used_squares, unsigned depth)
{
    if (mask == 0) return 1U;
    Shared *shared = worker->shared;
    const uint64_t key = state_key(mask, used_squares);
    uint64_t memoized;
    MemoToken token;
    if (!memo_claim(shared, key, &memoized, &token)) return memoized;

    const unsigned remaining_sum = subset_sum(shared, mask);
    if (!unused_squares_can_sum(shared, used_squares, remaining_sum)) {
        atomic_fetch_add_explicit(&shared->pruned_states, 1,
                                  memory_order_relaxed);
        memo_publish(shared, key, &token, 0U);
        return 0U;
    }

    const unsigned pivot_index = highest_bit_index(mask);
    const uint32_t pivot = UINT32_C(1) << pivot_index;
    const uint32_t rest = mask ^ pivot;
    const unsigned pivot_value = pivot_index + 1U;
    uint64_t total = 0;
    const unsigned rest_size = bit_count(rest);

    if (rest_size >= MITM_MIN_REST_SIZE) {
        uint32_t low_elements = 0;
        uint32_t high_elements = 0;
        uint32_t copy = rest;
        for (unsigned i = 0; copy != 0; ++i) {
            const uint32_t bit = copy & (0U - copy);
            copy ^= bit;
            if (i < rest_size / 2U)
                low_elements |= bit;
            else
                high_elements |= bit;
        }
        const size_t high_subset_count =
            (size_t)1U << bit_count(high_elements);
        const unsigned maximum_high_sum = subset_sum(shared, high_elements);
        uint32_t counts[MAX_SUM + 1U];
        uint32_t offsets[MAX_SUM + 2U];
        memset(counts, 0,
               (maximum_high_sum + 1U) * sizeof(*counts));
        uint32_t high = high_elements;
        for (;;) {
            ++counts[subset_sum(shared, high)];
            if (high == 0) break;
            high = (high - 1U) & high_elements;
        }
        offsets[0] = 0;
        for (unsigned sum = 0; sum <= maximum_high_sum; ++sum)
            offsets[sum + 1U] = offsets[sum] + counts[sum];

        uint32_t *grouped = mitm_workspace(worker, depth, high_subset_count);
        uint32_t cursor[MAX_SUM + 1U];
        memcpy(cursor, offsets,
               (maximum_high_sum + 1U) * sizeof(*cursor));
        high = high_elements;
        for (;;) {
            const unsigned sum = subset_sum(shared, high);
            grouped[cursor[sum]++] = high;
            if (high == 0) break;
            high = (high - 1U) & high_elements;
        }

        const unsigned maximum_block_sum =
            pivot_value + subset_sum(shared, rest);
        uint32_t low = low_elements;
        for (;;) {
            const unsigned low_value = subset_sum(shared, low);
            for (unsigned root = shared->ceil_root[pivot_value + low_value];
                 root <= maximum_block_sum / root; ++root) {
                const unsigned square = root * root;
                const uint32_t square_mask = UINT32_C(1) << (root - 1U);
                if (!square_choice_can_finish(shared, used_squares,
                                              square_mask, remaining_sum,
                                              square))
                    continue;
                const unsigned high_value =
                    square - pivot_value - low_value;
                if (high_value > maximum_high_sum) continue;
                for (uint32_t i = offsets[high_value];
                     i < offsets[high_value + 1U]; ++i) {
                    const uint32_t block_rest = low | grouped[i];
                    checked_add(&total,
                                count_partitions(worker, rest ^ block_rest,
                                                 used_squares | square_mask,
                                                 depth + 1U));
                }
            }
            if (low == 0) break;
            low = (low - 1U) & low_elements;
        }
    } else {
        uint32_t block_rest = rest;
        for (;;) {
            const unsigned block_sum =
                pivot_value + subset_sum(shared, block_rest);
            const uint32_t square_mask = shared->square_bit[block_sum];
            if (square_choice_can_finish(shared, used_squares, square_mask,
                                         remaining_sum, block_sum))
                checked_add(&total,
                            count_partitions(worker, rest ^ block_rest,
                                             used_squares | square_mask,
                                             depth + 1U));
            if (block_rest == 0) break;
            block_rest = (block_rest - 1U) & rest;
        }
    }

    memo_publish(shared, key, &token, total);
    return total;
}

static void initialize_tables(Shared *shared)
{
    shared->low_sum[0] = 0;
    for (uint32_t mask = 1; mask < LOW_SIZE; ++mask) {
        const uint32_t bit = mask & (0U - mask);
        shared->low_sum[mask] =
            (uint16_t)(shared->low_sum[mask ^ bit] +
                       highest_bit_index(bit) + 1U);
    }
    shared->high_sum[0] = 0;
    for (uint32_t mask = 1; mask < HIGH_SIZE; ++mask) {
        const uint32_t bit = mask & (0U - mask);
        shared->high_sum[mask] =
            (uint16_t)(shared->high_sum[mask ^ bit] + LOW_BITS +
                       highest_bit_index(bit) + 1U);
    }
    for (unsigned root = 1; root <= MAX_ROOT; ++root)
        shared->square_bit[root * root] = UINT32_C(1) << (root - 1U);
    unsigned root = 0;
    for (unsigned value = 0; value <= MAX_SUM; ++value) {
        while (root * root < value) ++root;
        shared->ceil_root[value] = (uint8_t)root;
    }

    const size_t word_count = (size_t)SQUARE_MASK_COUNT * REACH_WORDS;
    if (word_count > SIZE_MAX / sizeof(*shared->reachable))
        die("square reachability allocation size overflow");
    shared->reachable = calloc(word_count, sizeof(*shared->reachable));
    if (shared->reachable == NULL)
        die("could not allocate square reachability table");
    const uint32_t full = SQUARE_MASK_COUNT - 1U;
    shared->reachable[(size_t)full * REACH_WORDS] = UINT64_C(1);
    for (uint32_t used = full; used-- > 0U;) {
        const uint32_t available = (~used) & full;
        const uint32_t bit = available & (0U - available);
        const unsigned chosen_root = highest_bit_index(bit) + 1U;
        const unsigned shift = chosen_root * chosen_root;
        const uint64_t *source =
            &shared->reachable[(size_t)(used | bit) * REACH_WORDS];
        uint64_t *destination =
            &shared->reachable[(size_t)used * REACH_WORDS];
        memcpy(destination, source, REACH_WORDS * sizeof(*destination));
        const unsigned word_shift = shift / 64U;
        const unsigned bit_shift = shift % 64U;
        for (unsigned word = 0; word < REACH_WORDS; ++word) {
            const unsigned target = word + word_shift;
            if (target < REACH_WORDS)
                destination[target] |= source[word] << bit_shift;
            if (bit_shift != 0 && target + 1U < REACH_WORDS)
                destination[target + 1U] |=
                    source[word] >> (64U - bit_shift);
        }
    }
}

static size_t memo_capacity_for_n(unsigned n)
{
    const unsigned bits = n > 18U ? n - 2U : 16U;
    return (size_t)1U << bits;
}

static void reset_memo_between_terms(Shared *shared, size_t new_capacity,
                                     unsigned new_n)
{
    ConcurrentMemo *memo = &shared->memo;
    if (new_capacity > SIZE_MAX / sizeof(*memo->tags) ||
        new_capacity > SIZE_MAX / sizeof(*memo->values))
        die("concurrent memo allocation size overflow");
    fprintf(stderr, "preparing n=%u: fresh memo with %zu slots\n",
            new_n, new_capacity);
    if (fflush(stderr) == EOF) die("could not flush memo reset output");
    free(memo->tags);
    free(memo->values);
    memo->tags = calloc(new_capacity, sizeof(*memo->tags));
    memo->values = malloc(new_capacity * sizeof(*memo->values));
    if (memo->tags == NULL || memo->values == NULL)
        die("could not allocate fresh concurrent memo table");
    memo->capacity = new_capacity;
    atomic_store_explicit(&memo->size, 0, memory_order_relaxed);
    shared->n = new_n;
}

static void grow_memo_between_terms(Shared *shared, size_t new_capacity,
                                    unsigned new_n)
{
    ConcurrentMemo *memo = &shared->memo;
    if (new_capacity <= memo->capacity) {
        shared->n = new_n;
        return;
    }
    if (new_capacity > SIZE_MAX / sizeof(*memo->tags) ||
        new_capacity > SIZE_MAX / sizeof(*memo->values))
        die("concurrent memo allocation size overflow");
    const size_t old_size =
        atomic_load_explicit(&memo->size, memory_order_relaxed);
    if (old_size > SIZE_MAX / sizeof(uint64_t))
        die("memo compaction allocation size overflow");

    fprintf(stderr, "preparing n=%u: memo %zu -> %zu slots\n",
            new_n, memo->capacity, new_capacity);
    if (fflush(stderr) == EOF) die("could not flush memo growth output");
    const double started = monotonic_seconds();
    uint64_t *saved_keys = old_size == 0 ? NULL
        : malloc(old_size * sizeof(*saved_keys));
    uint64_t *saved_values = old_size == 0 ? NULL
        : malloc(old_size * sizeof(*saved_values));
    if (old_size != 0 && (saved_keys == NULL || saved_values == NULL))
        die("could not compact memo entries before growing");
    size_t saved = 0;
    for (size_t i = 0; i < memo->capacity; ++i) {
        const uint64_t tag =
            atomic_load_explicit(&memo->tags[i], memory_order_relaxed);
        if (tag == 0) continue;
        if ((tag & UINT64_C(1)) != 0)
            die("busy memo entry found between terms");
        if (saved == old_size)
            die("memo contains more entries than its recorded size");
        saved_keys[saved] = tag >> 1U;
        saved_values[saved] = memo->values[i];
        ++saved;
    }
    if (saved != old_size) die("memo size mismatch between terms");

    _Atomic uint64_t *new_tags =
        calloc(new_capacity, sizeof(*new_tags));
    if (new_tags == NULL) die("could not allocate grown memo keys");
    free(memo->tags);
    free(memo->values);
    uint64_t *new_values = malloc(new_capacity * sizeof(*new_values));
    if (new_values == NULL) die("could not allocate grown memo values");
    for (size_t i = 0; i < saved; ++i) {
        const uint64_t key = saved_keys[i];
        size_t index = (size_t)hash_key(key) & (new_capacity - 1U);
        while (atomic_load_explicit(&new_tags[index],
                                    memory_order_relaxed) != 0)
            index = (index + 1U) & (new_capacity - 1U);
        new_values[index] = saved_values[i];
        atomic_store_explicit(&new_tags[index], key << 1U,
                              memory_order_relaxed);
    }
    free(saved_keys);
    free(saved_values);
    memo->tags = new_tags;
    memo->values = new_values;
    memo->capacity = new_capacity;
    shared->n = new_n;
    fprintf(stderr, "preparing n=%u: memo ready in %.1fs\n",
            new_n, monotonic_seconds() - started);
    if (fflush(stderr) == EOF) die("could not flush memo growth output");
}

static void shared_prepare_n(Shared *shared, unsigned n)
{
    if (n < shared->n) die("internal attempt to shrink shared context");
    const size_t capacity = memo_capacity_for_n(n);
    if (n >= 25U && n != shared->n)
        reset_memo_between_terms(shared, capacity, n);
    else
        grow_memo_between_terms(shared, capacity, n);
}

static Shared *shared_create(unsigned n, unsigned thread_count)
{
    Shared *shared = calloc(1, sizeof(*shared));
    if (shared == NULL) die("could not allocate shared DP context");
    shared->thread_count = thread_count;
    initialize_tables(shared);
    shared_prepare_n(shared, n);
    if (shared->memo.capacity == 0) die("internal zero memo capacity");
    if (shared->memo.tags == NULL) {
        shared->memo.tags =
            calloc(shared->memo.capacity, sizeof(*shared->memo.tags));
        shared->memo.values =
            malloc(shared->memo.capacity * sizeof(*shared->memo.values));
        if (shared->memo.tags == NULL || shared->memo.values == NULL)
            die("could not allocate concurrent memo table");
    }
    return shared;
}

static void worker_destroy(Worker *worker)
{
    for (unsigned i = 0; i < MAX_N; ++i)
        free(worker->mitm_grouped[i]);
}

static void shared_destroy(Shared *shared)
{
    free(shared->memo.tags);
    free(shared->memo.values);
    free(shared->reachable);
    free(shared);
}

typedef struct {
    Shared *shared;
    RootTask *tasks;
    size_t task_count;
    uint32_t rest;
    _Atomic size_t next_task;
    _Atomic size_t completed_tasks;
    _Atomic bool stop_progress;
    Worker *workers;
    uint64_t *results;
    uint64_t initial_state_count;
    double start_time;
    unsigned term;
} RootQueue;

typedef struct {
    RootQueue *queue;
    unsigned worker_index;
} ThreadArgument;

static void report_progress(const RootQueue *queue, bool finished)
{
    const size_t completed =
        atomic_load_explicit(&queue->completed_tasks, memory_order_relaxed);
    const uint64_t states =
        atomic_load_explicit(&queue->shared->computed_states,
                             memory_order_relaxed);
    const double percent = queue->task_count == 0 ? 100.0
        : 100.0 * (double)completed / (double)queue->task_count;
    fprintf(stderr,
            "progress n=%u: root jobs %zu/%zu (%.1f%%), "
            "new states=%" PRIu64 ", elapsed=%.1fs%s\n",
            queue->term, completed, queue->task_count, percent,
            states - queue->initial_state_count,
            monotonic_seconds() - queue->start_time,
            finished ? ", done" : "");
    if (fflush(stderr) == EOF) die("could not flush progress output");
}

static void *progress_worker(void *opaque)
{
    RootQueue *queue = opaque;
    double next_report = queue->start_time + PROGRESS_INTERVAL_SECONDS;
    const struct timespec pause = {0, PROGRESS_POLL_NANOSECONDS};
    while (!atomic_load_explicit(&queue->stop_progress,
                                 memory_order_acquire)) {
        (void)nanosleep(&pause, NULL);
        const double now = monotonic_seconds();
        if (now >= next_report &&
            !atomic_load_explicit(&queue->stop_progress,
                                  memory_order_acquire)) {
            report_progress(queue, false);
            do {
                next_report += PROGRESS_INTERVAL_SECONDS;
            } while (next_report <= now);
        }
    }
    return NULL;
}

static RootTask *build_root_tasks(const Shared *shared, uint32_t mask,
                                  size_t *result_count)
{
    const unsigned pivot_index = highest_bit_index(mask);
    const unsigned pivot_value = pivot_index + 1U;
    const uint32_t pivot = UINT32_C(1) << pivot_index;
    const uint32_t rest = mask ^ pivot;
    const unsigned rest_size = bit_count(rest);
    const unsigned remaining_sum = subset_sum(shared, mask);
    uint32_t low_elements = 0;
    uint32_t high_elements = 0;
    uint32_t copy = rest;
    for (unsigned i = 0; copy != 0; ++i) {
        const uint32_t bit = copy & (0U - copy);
        copy ^= bit;
        if (i < rest_size / 2U)
            low_elements |= bit;
        else
            high_elements |= bit;
    }
    const size_t high_subset_count =
        (size_t)1U << bit_count(high_elements);
    const unsigned maximum_high_sum = subset_sum(shared, high_elements);
    uint32_t counts[MAX_SUM + 1U];
    uint32_t offsets[MAX_SUM + 2U];
    uint32_t cursor[MAX_SUM + 1U];
    memset(counts, 0,
           (maximum_high_sum + 1U) * sizeof(*counts));
    uint32_t high = high_elements;
    for (;;) {
        ++counts[subset_sum(shared, high)];
        if (high == 0) break;
        high = (high - 1U) & high_elements;
    }
    offsets[0] = 0;
    for (unsigned sum = 0; sum <= maximum_high_sum; ++sum)
        offsets[sum + 1U] = offsets[sum] + counts[sum];
    memcpy(cursor, offsets,
           (maximum_high_sum + 1U) * sizeof(*cursor));
    uint32_t *grouped = malloc(high_subset_count * sizeof(*grouped));
    if (grouped == NULL) die("could not allocate root subset groups");
    high = high_elements;
    for (;;) {
        const unsigned sum = subset_sum(shared, high);
        grouped[cursor[sum]++] = high;
        if (high == 0) break;
        high = (high - 1U) & high_elements;
    }

    const unsigned maximum_block_sum = pivot_value + subset_sum(shared, rest);
    size_t total = 0;
    uint32_t low = low_elements;
    for (;;) {
        const unsigned low_value = subset_sum(shared, low);
        for (unsigned root = shared->ceil_root[pivot_value + low_value];
             root <= maximum_block_sum / root; ++root) {
            const unsigned square = root * root;
            const uint32_t square_mask = UINT32_C(1) << (root - 1U);
            if (!square_choice_can_finish(shared, 0U, square_mask,
                                          remaining_sum, square))
                continue;
            const unsigned high_value = square - pivot_value - low_value;
            if (high_value <= maximum_high_sum) {
                const size_t add = counts[high_value];
                if (SIZE_MAX - total < add)
                    die("root task count overflow");
                total += add;
            }
        }
        if (low == 0) break;
        low = (low - 1U) & low_elements;
    }
    if (total > SIZE_MAX / sizeof(RootTask))
        die("root task allocation size overflow");
    RootTask *tasks = total == 0 ? NULL
        : malloc(total * sizeof(*tasks));
    if (total != 0 && tasks == NULL)
        die("could not allocate root task list");

    size_t used = 0;
    low = low_elements;
    for (;;) {
        const unsigned low_value = subset_sum(shared, low);
        for (unsigned root = shared->ceil_root[pivot_value + low_value];
             root <= maximum_block_sum / root; ++root) {
            const unsigned square = root * root;
            const uint32_t square_mask = UINT32_C(1) << (root - 1U);
            if (!square_choice_can_finish(shared, 0U, square_mask,
                                          remaining_sum, square))
                continue;
            const unsigned high_value = square - pivot_value - low_value;
            if (high_value > maximum_high_sum) continue;
            for (uint32_t i = offsets[high_value];
                 i < offsets[high_value + 1U]; ++i) {
                tasks[used].block_rest = low | grouped[i];
                tasks[used].square_mask = square_mask;
                ++used;
            }
        }
        if (low == 0) break;
        low = (low - 1U) & low_elements;
    }
    free(grouped);
    if (used != total) die("internal root task count mismatch");
    *result_count = total;
    return tasks;
}

static void *root_worker(void *opaque)
{
    ThreadArgument *argument = opaque;
    RootQueue *queue = argument->queue;
    Worker *worker = &queue->workers[argument->worker_index];
    uint64_t total = 0;
    for (;;) {
        const size_t begin =
            atomic_fetch_add_explicit(&queue->next_task, TASK_CHUNK,
                                      memory_order_relaxed);
        if (begin >= queue->task_count) break;
        size_t end = begin + TASK_CHUNK;
        if (end > queue->task_count) end = queue->task_count;
        for (size_t i = begin; i < end; ++i) {
            const RootTask task = queue->tasks[i];
            checked_add(&total,
                        count_partitions(worker,
                                         queue->rest ^ task.block_rest,
                                         task.square_mask, 0U));
        }
        atomic_fetch_add_explicit(&queue->completed_tasks, end - begin,
                                  memory_order_relaxed);
    }
    queue->results[argument->worker_index] = total;
    return NULL;
}

static uint64_t count_full(Shared *shared, uint32_t mask)
{
    if (mask == 0) return 1U;
    Worker serial_worker;
    memset(&serial_worker, 0, sizeof(serial_worker));
    serial_worker.shared = shared;
    const unsigned term = bit_count(mask);
    if (term < PARALLEL_MIN_N ||
        (shared->thread_count == 1U && term < PROGRESS_MIN_N)) {
        const uint64_t result =
            count_partitions(&serial_worker, mask, 0U, 0U);
        worker_destroy(&serial_worker);
        return result;
    }

    const uint64_t root_key = state_key(mask, 0U);
    uint64_t memoized;
    MemoToken root_token;
    if (!memo_claim(shared, root_key, &memoized, &root_token)) {
        worker_destroy(&serial_worker);
        return memoized;
    }
    if (!unused_squares_can_sum(shared, 0U, subset_sum(shared, mask))) {
        atomic_fetch_add_explicit(&shared->pruned_states, 1,
                                  memory_order_relaxed);
        memo_publish(shared, root_key, &root_token, 0U);
        worker_destroy(&serial_worker);
        return 0U;
    }

    size_t task_count = 0;
    RootTask *tasks = build_root_tasks(shared, mask, &task_count);
    const unsigned thread_count = shared->thread_count;
    RootQueue queue;
    memset(&queue, 0, sizeof(queue));
    queue.shared = shared;
    queue.tasks = tasks;
    queue.task_count = task_count;
    queue.term = term;
    queue.initial_state_count =
        atomic_load_explicit(&shared->computed_states, memory_order_relaxed);
    queue.start_time = monotonic_seconds();
    queue.rest = mask ^ (UINT32_C(1) << highest_bit_index(mask));
    queue.workers = calloc(thread_count, sizeof(*queue.workers));
    queue.results = calloc(thread_count, sizeof(*queue.results));
    ThreadArgument *arguments = calloc(thread_count, sizeof(*arguments));
    pthread_t *threads = thread_count > 1U
        ? calloc(thread_count - 1U, sizeof(*threads)) : NULL;
    pthread_t progress_thread;
    const bool show_progress = term >= PROGRESS_MIN_N;
    if (queue.workers == NULL || queue.results == NULL || arguments == NULL ||
        (thread_count > 1U && threads == NULL))
        die("could not allocate root worker data");
    for (unsigned i = 0; i < thread_count; ++i) {
        queue.workers[i].shared = shared;
        arguments[i].queue = &queue;
        arguments[i].worker_index = i;
    }
    if (show_progress) {
        report_progress(&queue, false);
        const int error =
            pthread_create(&progress_thread, NULL, progress_worker, &queue);
        if (error != 0) {
            fprintf(stderr, "error: pthread_create: %s\n", strerror(error));
            exit(EXIT_FAILURE);
        }
    }
    for (unsigned i = 1; i < thread_count; ++i) {
        const int error =
            pthread_create(&threads[i - 1U], NULL, root_worker, &arguments[i]);
        if (error != 0) {
            fprintf(stderr, "error: pthread_create: %s\n", strerror(error));
            exit(EXIT_FAILURE);
        }
    }
    root_worker(&arguments[0]);
    for (unsigned i = 1; i < thread_count; ++i) {
        const int error = pthread_join(threads[i - 1U], NULL);
        if (error != 0) {
            fprintf(stderr, "error: pthread_join: %s\n", strerror(error));
            exit(EXIT_FAILURE);
        }
    }
    if (show_progress) {
        atomic_store_explicit(&queue.stop_progress, true,
                              memory_order_release);
        const int error = pthread_join(progress_thread, NULL);
        if (error != 0) {
            fprintf(stderr, "error: pthread_join: %s\n", strerror(error));
            exit(EXIT_FAILURE);
        }
    }

    uint64_t result = 0;
    for (unsigned i = 0; i < thread_count; ++i) {
        checked_add(&result, queue.results[i]);
        worker_destroy(&queue.workers[i]);
    }
    memo_publish(shared, root_key, &root_token, result);
    if (show_progress) report_progress(&queue, true);
    free(threads);
    free(arguments);
    free(queue.results);
    free(queue.workers);
    free(tasks);
    worker_destroy(&serial_worker);
    return result;
}

static FILE *open_bfile(void)
{
    FILE *stream = fopen(BFILE_NAME, "w");
    if (stream == NULL) {
        fprintf(stderr, "error: could not create %s: %s\n",
                BFILE_NAME, strerror(errno));
        exit(EXIT_FAILURE);
    }
    return stream;
}

static void write_bfile_term(FILE *stream, unsigned n, uint64_t value)
{
    if (fprintf(stream, "%u %" PRIu64 "\n", n, value) < 0 ||
        fflush(stream) != 0 || fsync(fileno(stream)) != 0) {
        fprintf(stderr, "error: could not synchronize %s: %s\n",
                BFILE_NAME, strerror(errno));
        exit(EXIT_FAILURE);
    }
}

static void close_bfile(FILE *stream)
{
    if (fclose(stream) != 0) {
        fprintf(stderr, "error: could not close %s: %s\n",
                BFILE_NAME, strerror(errno));
        exit(EXIT_FAILURE);
    }
}

static void usage(FILE *stream, const char *program)
{
    fprintf(stream,
            "Usage: %s [--upto N | --target N] [--threads T] "
            "[--self-test] [--stats]\n"
            "  --upto N     print a(0)..a(N), 0 <= N <= %u (default %u)\n"
            "  --target N   print only a(N)\n"
            "               n=29 reserves about 2 GiB for the memo table\n"
            "  --threads T  use 1..64 workers (default: up to 8 CPUs)\n"
            "  --self-test  compare computed terms with regression values\n"
            "  --stats      report states, waits, and memo-table load\n"
            "  For n >= 24, progress is reported every 60 seconds.\n"
            "  Results are synchronized to " BFILE_NAME
            " after every term.\n"
            "  --help       show this help\n",
            program, MAX_N, DEFAULT_N);
}

int main(int argc, char **argv)
{
    unsigned n = DEFAULT_N;
    unsigned thread_count = default_thread_count();
    bool target_only = false;
    bool self_test = false;
    bool stats = false;
    for (int i = 1; i < argc; ++i) {
        if (strcmp(argv[i], "--upto") == 0) {
            if (++i == argc) die("--upto requires an argument");
            n = parse_n(argv[i]);
            target_only = false;
        } else if (strcmp(argv[i], "--target") == 0) {
            if (++i == argc) die("--target requires an argument");
            n = parse_n(argv[i]);
            target_only = true;
        } else if (strcmp(argv[i], "--threads") == 0) {
            if (++i == argc) die("--threads requires an argument");
            thread_count = parse_threads(argv[i]);
        } else if (strcmp(argv[i], "--self-test") == 0) {
            self_test = true;
        } else if (strcmp(argv[i], "--stats") == 0) {
            stats = true;
        } else if (strcmp(argv[i], "--help") == 0 ||
                   strcmp(argv[i], "-h") == 0) {
            usage(stdout, argv[0]);
            return EXIT_SUCCESS;
        } else {
            fprintf(stderr, "error: unknown argument: %s\n", argv[i]);
            usage(stderr, argv[0]);
            return EXIT_FAILURE;
        }
    }

    const unsigned initial_n = target_only ? n : 0U;
    Shared *shared = shared_create(initial_n, thread_count);
    FILE *bfile = open_bfile();
    const unsigned first = target_only ? n : 0U;
    for (unsigned k = first; k <= n; ++k) {
        shared_prepare_n(shared, k);
        const uint32_t mask = k == 0 ? 0U : (UINT32_C(1) << k) - 1U;
        const uint64_t value = count_full(shared, mask);
        if (self_test && value != known[k]) {
            fprintf(stderr,
                    "self-test failed at n=%u: got %" PRIu64
                    ", expected %" PRIu64 "\n",
                    k, value, known[k]);
            close_bfile(bfile);
            shared_destroy(shared);
            return EXIT_FAILURE;
        }
        write_bfile_term(bfile, k, value);
        printf("%u %" PRIu64 "\n", k, value);
        if (fflush(stdout) == EOF) die("could not flush sequence output");
    }
    if (self_test)
        fprintf(stderr, "self-test passed through known n=%u\n", n);
    if (stats)
        fprintf(stderr,
                "computed states total: %" PRIu64 ", nonzero: %" PRIu64
                ", pruned: %" PRIu64 ", waits: %" PRIu64
                ", table: %zu/%zu\n",
                atomic_load_explicit(&shared->computed_states,
                                     memory_order_relaxed),
                atomic_load_explicit(&shared->nonzero_states,
                                     memory_order_relaxed),
                atomic_load_explicit(&shared->pruned_states,
                                     memory_order_relaxed),
                atomic_load_explicit(&shared->wait_count,
                                     memory_order_relaxed),
                atomic_load_explicit(&shared->memo.size,
                                     memory_order_relaxed),
                shared->memo.capacity);
    close_bfile(bfile);
    shared_destroy(shared);
    return EXIT_SUCCESS;
}
