/*
 * A278339: number of set partitions of [n] into blocks whose element sums
 * are distinct squares.
 *
 * Let F(M,U) count completions of the remaining element mask M when U is
 * the set of square sums already used.  Put the largest element of M in a
 * distinguished block B.  This fixes the order in which blocks are removed
 * and avoids counting a partition more than once:
 *
 *   F(0,U) = 1,
 *   F(M,U) = sum F(M \\ B, U union {sum(B)}),
 *
 * where B contains max(M), sum(B) is a square, and that square is not in U.
 * The complete pair (M,U) is the memo key, so hash collisions cannot change
 * the result.  Candidate blocks are generated by meet-in-the-middle subset
 * sum for large states and ordinary submask enumeration for small states.
 *
 * A necessary condition for a state to succeed is that sum(M) be a subset
 * sum of the unused squares.  Reachability bitsets for all 2^20 used-square
 * masks are precomputed once (the possible positive squares are 1^2..20^2
 * because 1+...+29=435).  This provides an exact, inexpensive zero test.
 * Counts, additions, allocations, and table growth are checked.  Known terms
 * are used only by --self-test after a value has been computed.
 *
 * Build:
 *   clang -O3 -march=native -std=c11 -Wall -Wextra -Wpedantic \
 *       278339_01.c -o 278339_01
 *
 * Examples:
 *   ./278339_01 --upto 24 --self-test --stats
 *   ./278339_01 --target 29 --self-test --stats
 *
 * Each computed result is also written to b278339_01.txt in the current
 * directory.  The file is flushed and synchronized after every term, so a
 * completed prefix remains available if a long --upto run is interrupted.
 */

#include <errno.h>
#include <inttypes.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#define MAX_N 29U
#define DEFAULT_N 24U
#define KNOWN_N 29U
#ifndef MITM_MIN_REST_SIZE
#define MITM_MIN_REST_SIZE 8U
#endif
#define INITIAL_MEMO_CAPACITY ((size_t)1U << 16U)
#define LOW_BITS 16U
#define LOW_SIZE (UINT32_C(1) << LOW_BITS)
#define HIGH_BITS (MAX_N - LOW_BITS)
#define HIGH_SIZE (UINT32_C(1) << HIGH_BITS)
#define MAX_SUM (MAX_N * (MAX_N + 1U) / 2U)
#define MAX_ROOT 20U
#define SQUARE_MASK_COUNT (UINT32_C(1) << MAX_ROOT)
#define REACH_WORDS ((MAX_SUM + 64U) / 64U)
#define BFILE_NAME "b278339_01.txt"

typedef struct {
    uint64_t *keys;
    uint64_t *values;
    size_t capacity;
    size_t size;
} Memo;

typedef struct {
    Memo memo;
    uint64_t computed_states;
    uint64_t nonzero_states;
    uint64_t pruned_states;
    uint32_t *mitm_grouped[MAX_N];
    size_t mitm_capacity[MAX_N];
    uint64_t *reachable;
    uint16_t low_sum[LOW_SIZE];
    uint16_t high_sum[HIGH_SIZE];
    uint32_t square_bit[MAX_SUM + 1U];
    uint8_t ceil_root[MAX_SUM + 1U];
} Context;

static const uint64_t known[KNOWN_N + 1U] = {
    UINT64_C(1), UINT64_C(1), UINT64_C(0), UINT64_C(0),
    UINT64_C(1), UINT64_C(0), UINT64_C(1), UINT64_C(0),
    UINT64_C(1), UINT64_C(23), UINT64_C(9), UINT64_C(41),
    UINT64_C(248), UINT64_C(277), UINT64_C(1556), UINT64_C(2854),
    UINT64_C(5233), UINT64_C(20701), UINT64_C(145137),
    UINT64_C(1626890), UINT64_C(4118910), UINT64_C(9963276),
    UINT64_C(9260756), UINT64_C(64027363), UINT64_C(365237571),
    UINT64_C(1002679107), UINT64_C(21594036300),
    UINT64_C(24465529531), UINT64_C(144914973347),
    UINT64_C(1921444799766)
};

static _Noreturn void die(const char *message)
{
    fprintf(stderr, "error: %s\n", message);
    exit(EXIT_FAILURE);
}

static unsigned parse_n(const char *text)
{
    errno = 0;
    char *end = NULL;
    const uintmax_t value = strtoumax(text, &end, 10);
    if (errno != 0 || end == text || *end != '\0' || value > MAX_N) {
        fprintf(stderr, "error: n must be in 0..%u: %s\n", MAX_N, text);
        exit(EXIT_FAILURE);
    }
    return (unsigned)value;
}

static unsigned highest_bit_index(uint32_t mask)
{
#if defined(__clang__) || defined(__GNUC__)
    return 31U - (unsigned)__builtin_clz(mask);
#else
    unsigned index = 0;
    while (mask >>= 1U) ++index;
    return index;
#endif
}

static unsigned bit_count(uint32_t mask)
{
#if defined(__clang__) || defined(__GNUC__)
    return (unsigned)__builtin_popcount(mask);
#else
    unsigned count = 0;
    while (mask != 0) {
        mask &= mask - 1U;
        ++count;
    }
    return count;
#endif
}

static uint16_t subset_sum(const Context *context, uint32_t mask)
{
    return (uint16_t)(context->low_sum[mask & (LOW_SIZE - 1U)] +
                      context->high_sum[mask >> LOW_BITS]);
}

static uint64_t hash_key(uint64_t key)
{
    key ^= key >> 30U;
    key *= UINT64_C(0xbf58476d1ce4e5b9);
    key ^= key >> 27U;
    key *= UINT64_C(0x94d049bb133111eb);
    key ^= key >> 31U;
    return key;
}

static uint64_t state_key(uint32_t mask, uint32_t used_squares)
{
    return (((uint64_t)used_squares << MAX_N) | mask) + 1U;
}

static bool memo_get(const Memo *memo, uint64_t key, uint64_t *value)
{
    size_t index = (size_t)hash_key(key) & (memo->capacity - 1U);
    while (memo->keys[index] != 0) {
        if (memo->keys[index] == key) {
            *value = memo->values[index];
            return true;
        }
        index = (index + 1U) & (memo->capacity - 1U);
    }
    return false;
}

static void memo_insert_raw(Memo *memo, uint64_t key, uint64_t value)
{
    size_t index = (size_t)hash_key(key) & (memo->capacity - 1U);
    while (memo->keys[index] != 0)
        index = (index + 1U) & (memo->capacity - 1U);
    memo->keys[index] = key;
    memo->values[index] = value;
    ++memo->size;
}

static void memo_grow(Memo *memo)
{
    if (memo->capacity > SIZE_MAX / 2U)
        die("memo hash table capacity overflow");
    const size_t new_capacity = memo->capacity * 2U;
    if (new_capacity > SIZE_MAX / sizeof(*memo->keys) ||
        new_capacity > SIZE_MAX / sizeof(*memo->values))
        die("memo hash table allocation size overflow");

    uint64_t *new_keys = calloc(new_capacity, sizeof(*new_keys));
    uint64_t *new_values = malloc(new_capacity * sizeof(*new_values));
    if (new_keys == NULL || new_values == NULL)
        die("could not grow the memo hash table");

    uint64_t *old_keys = memo->keys;
    uint64_t *old_values = memo->values;
    const size_t old_capacity = memo->capacity;
    memo->keys = new_keys;
    memo->values = new_values;
    memo->capacity = new_capacity;
    memo->size = 0;
    for (size_t i = 0; i < old_capacity; ++i) {
        if (old_keys[i] != 0)
            memo_insert_raw(memo, old_keys[i], old_values[i]);
    }
    free(old_keys);
    free(old_values);
}

static void memo_set(Memo *memo, uint64_t key, uint64_t value)
{
    if ((memo->size + 1U) * 10U >= memo->capacity * 7U)
        memo_grow(memo);
    memo_insert_raw(memo, key, value);
}

static bool unused_squares_can_sum(const Context *context,
                                   uint32_t used_squares,
                                   unsigned sum)
{
    const size_t offset = (size_t)used_squares * REACH_WORDS;
    return ((context->reachable[offset + sum / 64U] >> (sum % 64U)) &
            UINT64_C(1)) != 0;
}

static bool square_choice_can_finish(const Context *context,
                                     uint32_t used_squares,
                                     uint32_t square_mask,
                                     unsigned remaining_sum,
                                     unsigned square)
{
    return square_mask != 0 && (used_squares & square_mask) == 0 &&
           square <= remaining_sum &&
           unused_squares_can_sum(context, used_squares | square_mask,
                                  remaining_sum - square);
}

static uint32_t *mitm_workspace(Context *context, unsigned depth,
                                size_t needed)
{
    if (depth >= MAX_N) die("internal recursion depth overflow");
    if (context->mitm_capacity[depth] < needed) {
        if (needed > SIZE_MAX / sizeof(*context->mitm_grouped[depth]))
            die("meet-in-the-middle workspace is too large");
        uint32_t *replacement =
            realloc(context->mitm_grouped[depth],
                    needed * sizeof(*context->mitm_grouped[depth]));
        if (replacement == NULL)
            die("could not allocate meet-in-the-middle workspace");
        context->mitm_grouped[depth] = replacement;
        context->mitm_capacity[depth] = needed;
    }
    return context->mitm_grouped[depth];
}

static void checked_add(uint64_t *total, uint64_t addend)
{
    if (UINT64_MAX - *total < addend)
        die("uint64_t overflow while counting partitions");
    *total += addend;
}

static uint64_t count_partitions(Context *context, uint32_t mask,
                                 uint32_t used_squares, unsigned depth)
{
    if (mask == 0) return 1U;

    const uint64_t key = state_key(mask, used_squares);
    uint64_t memoized;
    if (memo_get(&context->memo, key, &memoized)) return memoized;

    const unsigned remaining_sum = subset_sum(context, mask);
    if (!unused_squares_can_sum(context, used_squares, remaining_sum)) {
        memo_set(&context->memo, key, 0U);
        ++context->computed_states;
        ++context->pruned_states;
        return 0U;
    }

    const unsigned pivot_index = highest_bit_index(mask);
    const uint32_t pivot = UINT32_C(1) << pivot_index;
    const uint32_t rest = mask ^ pivot;
    const unsigned pivot_value = pivot_index + 1U;
    uint64_t total = 0;

    const unsigned rest_size = bit_count(rest);
    if (rest_size >= MITM_MIN_REST_SIZE) {
        uint32_t low_elements = 0;
        uint32_t high_elements = 0;
        uint32_t copy = rest;
        for (unsigned i = 0; copy != 0; ++i) {
            const uint32_t bit = copy & (0U - copy);
            copy ^= bit;
            if (i < rest_size / 2U)
                low_elements |= bit;
            else
                high_elements |= bit;
        }

        const unsigned high_count = bit_count(high_elements);
        const size_t high_subset_count = (size_t)1U << high_count;
        const unsigned maximum_high_sum =
            subset_sum(context, high_elements);
        uint32_t counts[MAX_SUM + 1U];
        uint32_t offsets[MAX_SUM + 2U];
        memset(counts, 0,
               (maximum_high_sum + 1U) * sizeof(*counts));
        uint32_t high = high_elements;
        for (;;) {
            ++counts[subset_sum(context, high)];
            if (high == 0) break;
            high = (high - 1U) & high_elements;
        }
        offsets[0] = 0;
        for (unsigned sum = 0; sum <= maximum_high_sum; ++sum)
            offsets[sum + 1U] = offsets[sum] + counts[sum];

        uint32_t *grouped =
            mitm_workspace(context, depth, high_subset_count);
        uint32_t cursor[MAX_SUM + 1U];
        memcpy(cursor, offsets,
               (maximum_high_sum + 1U) * sizeof(*cursor));
        high = high_elements;
        for (;;) {
            const unsigned sum = subset_sum(context, high);
            grouped[cursor[sum]++] = high;
            if (high == 0) break;
            high = (high - 1U) & high_elements;
        }

        const unsigned maximum_block_sum =
            pivot_value + subset_sum(context, rest);
        uint32_t low = low_elements;
        for (;;) {
            const unsigned low_value = subset_sum(context, low);
            for (unsigned root = context->ceil_root[pivot_value + low_value];
                 root <= maximum_block_sum / root; ++root) {
                const uint32_t square = root * root;
                const uint32_t square_mask = UINT32_C(1) << (root - 1U);
                if (!square_choice_can_finish(context, used_squares,
                                              square_mask, remaining_sum,
                                              square))
                    continue;
                const unsigned high_value =
                    square - pivot_value - low_value;
                if (high_value > maximum_high_sum) continue;
                for (uint32_t i = offsets[high_value];
                     i < offsets[high_value + 1U]; ++i) {
                    const uint32_t block_rest = low | grouped[i];
                    checked_add(&total,
                                count_partitions(context,
                                                 rest ^ block_rest,
                                                 used_squares | square_mask,
                                                 depth + 1U));
                }
            }
            if (low == 0) break;
            low = (low - 1U) & low_elements;
        }
    } else {
        uint32_t block_rest = rest;
        for (;;) {
            const unsigned block_sum =
                pivot_value + subset_sum(context, block_rest);
            const uint32_t square_mask = context->square_bit[block_sum];
            if (square_choice_can_finish(context, used_squares, square_mask,
                                         remaining_sum, block_sum))
                checked_add(&total,
                            count_partitions(context, rest ^ block_rest,
                                             used_squares | square_mask,
                                             depth + 1U));
            if (block_rest == 0) break;
            block_rest = (block_rest - 1U) & rest;
        }
    }

    memo_set(&context->memo, key, total);
    ++context->computed_states;
    if (total != 0) ++context->nonzero_states;
    return total;
}

static void initialize_element_sums(Context *context)
{
    context->low_sum[0] = 0;
    for (uint32_t mask = 1; mask < LOW_SIZE; ++mask) {
        const uint32_t bit = mask & (0U - mask);
        context->low_sum[mask] =
            (uint16_t)(context->low_sum[mask ^ bit] +
                       highest_bit_index(bit) + 1U);
    }

    context->high_sum[0] = 0;
    for (uint32_t mask = 1; mask < HIGH_SIZE; ++mask) {
        const uint32_t bit = mask & (0U - mask);
        context->high_sum[mask] =
            (uint16_t)(context->high_sum[mask ^ bit] + LOW_BITS +
                       highest_bit_index(bit) + 1U);
    }
}

static void initialize_squares(Context *context)
{
    memset(context->square_bit, 0, sizeof(context->square_bit));
    for (unsigned root = 1; root <= MAX_ROOT; ++root)
        context->square_bit[root * root] =
            UINT32_C(1) << (root - 1U);

    unsigned root = 0;
    for (unsigned value = 0; value <= MAX_SUM; ++value) {
        while (root * root < value) ++root;
        context->ceil_root[value] = (uint8_t)root;
    }
}

static void initialize_reachability(Context *context)
{
    const size_t word_count = (size_t)SQUARE_MASK_COUNT * REACH_WORDS;
    if (word_count > SIZE_MAX / sizeof(*context->reachable))
        die("square reachability allocation size overflow");
    context->reachable = calloc(word_count, sizeof(*context->reachable));
    if (context->reachable == NULL)
        die("could not allocate square reachability table");

    const uint32_t full = SQUARE_MASK_COUNT - 1U;
    context->reachable[(size_t)full * REACH_WORDS] = UINT64_C(1);
    for (uint32_t used = full; used-- > 0U;) {
        const uint32_t available = (~used) & full;
        const uint32_t bit = available & (0U - available);
        const unsigned root = highest_bit_index(bit) + 1U;
        const unsigned shift = root * root;
        const uint64_t *source =
            &context->reachable[(size_t)(used | bit) * REACH_WORDS];
        uint64_t *destination =
            &context->reachable[(size_t)used * REACH_WORDS];
        memcpy(destination, source, REACH_WORDS * sizeof(*destination));
        const unsigned word_shift = shift / 64U;
        const unsigned bit_shift = shift % 64U;
        for (unsigned word = 0; word < REACH_WORDS; ++word) {
            if (source[word] == 0) continue;
            const unsigned target = word + word_shift;
            if (target < REACH_WORDS)
                destination[target] |= source[word] << bit_shift;
            if (bit_shift != 0 && target + 1U < REACH_WORDS)
                destination[target + 1U] |=
                    source[word] >> (64U - bit_shift);
        }
    }
}

static Context *context_create(void)
{
    Context *context = calloc(1, sizeof(*context));
    if (context == NULL) die("could not allocate the DP context");

    context->memo.capacity = INITIAL_MEMO_CAPACITY;
    context->memo.keys =
        calloc(context->memo.capacity, sizeof(*context->memo.keys));
    context->memo.values =
        malloc(context->memo.capacity * sizeof(*context->memo.values));
    if (context->memo.keys == NULL || context->memo.values == NULL)
        die("could not allocate the memo hash table");

    initialize_element_sums(context);
    initialize_squares(context);
    initialize_reachability(context);
    return context;
}

static void context_destroy(Context *context)
{
    free(context->memo.keys);
    free(context->memo.values);
    free(context->reachable);
    for (unsigned i = 0; i < MAX_N; ++i)
        free(context->mitm_grouped[i]);
    free(context);
}

static FILE *open_bfile(void)
{
    FILE *stream = fopen(BFILE_NAME, "w");
    if (stream == NULL) {
        fprintf(stderr, "error: could not create %s: %s\n",
                BFILE_NAME, strerror(errno));
        exit(EXIT_FAILURE);
    }
    return stream;
}

static void write_bfile_term(FILE *stream, unsigned n, uint64_t value)
{
    if (fprintf(stream, "%u %" PRIu64 "\n", n, value) < 0 ||
        fflush(stream) != 0) {
        fprintf(stderr, "error: could not write %s: %s\n",
                BFILE_NAME, strerror(errno));
        exit(EXIT_FAILURE);
    }
    const int descriptor = fileno(stream);
    if (descriptor < 0 || fsync(descriptor) != 0) {
        fprintf(stderr, "error: could not synchronize %s: %s\n",
                BFILE_NAME, strerror(errno));
        exit(EXIT_FAILURE);
    }
}

static void close_bfile(FILE *stream)
{
    if (fclose(stream) != 0) {
        fprintf(stderr, "error: could not close %s: %s\n",
                BFILE_NAME, strerror(errno));
        exit(EXIT_FAILURE);
    }
}

static void usage(FILE *stream, const char *program)
{
    fprintf(stream,
            "Usage: %s [--upto N | --target N] [--self-test] [--stats]\n"
            "  --upto N     print a(0)..a(N), 0 <= N <= %u (default %u)\n"
            "  --target N   print only a(N)\n"
            "               N >= 27 can take a long time and several GiB\n"
            "  --self-test  compare computed terms with regression values\n"
            "  --stats      report memoized and pruned state counts\n"
            "  Results are synchronized to " BFILE_NAME
            " after every term.\n"
            "  --help       show this help\n",
            program, MAX_N, DEFAULT_N);
}

int main(int argc, char **argv)
{
    unsigned n = DEFAULT_N;
    bool target_only = false;
    bool self_test = false;
    bool stats = false;

    for (int i = 1; i < argc; ++i) {
        if (strcmp(argv[i], "--upto") == 0) {
            if (++i == argc) die("--upto requires an argument");
            n = parse_n(argv[i]);
            target_only = false;
        } else if (strcmp(argv[i], "--target") == 0) {
            if (++i == argc) die("--target requires an argument");
            n = parse_n(argv[i]);
            target_only = true;
        } else if (strcmp(argv[i], "--self-test") == 0) {
            self_test = true;
        } else if (strcmp(argv[i], "--stats") == 0) {
            stats = true;
        } else if (strcmp(argv[i], "--help") == 0 ||
                   strcmp(argv[i], "-h") == 0) {
            usage(stdout, argv[0]);
            return EXIT_SUCCESS;
        } else {
            fprintf(stderr, "error: unknown argument: %s\n", argv[i]);
            usage(stderr, argv[0]);
            return EXIT_FAILURE;
        }
    }

    Context *context = context_create();
    FILE *bfile = open_bfile();
    const unsigned first = target_only ? n : 0U;
    for (unsigned k = first; k <= n; ++k) {
        const uint32_t mask =
            k == 0 ? 0U : (UINT32_C(1) << k) - 1U;
        const uint64_t value = count_partitions(context, mask, 0U, 0U);
        if (self_test && value != known[k]) {
            fprintf(stderr,
                    "self-test failed at n=%u: got %" PRIu64
                    ", expected %" PRIu64 "\n",
                    k, value, known[k]);
            close_bfile(bfile);
            context_destroy(context);
            return EXIT_FAILURE;
        }
        write_bfile_term(bfile, k, value);
        printf("%u %" PRIu64 "\n", k, value);
        if (fflush(stdout) == EOF) die("could not flush sequence output");
    }
    if (self_test)
        fprintf(stderr, "self-test passed through known n=%u\n", n);
    if (stats)
        fprintf(stderr,
                "memoized states: %" PRIu64 ", nonzero: %" PRIu64
                ", pruned: %" PRIu64 ", table: %zu/%zu\n",
                context->computed_states, context->nonzero_states,
                context->pruned_states, context->memo.size,
                context->memo.capacity);
    close_bfile(bfile);
    context_destroy(context);
    return EXIT_SUCCESS;
}
